version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    restart: unless-stopped
    volumes:
      - ./mqtt_broker/config:/mosquitto/config:rw
      - ./mqtt_broker/data:/mosquitto/data:rw
      - ./mqtt_broker/log:/mosquitto/log:rw

  # mqtt5 mqtt-explorer
  mqtt-explorer:
    image: emqx/mqttx-web
    container_name: mqtt-explorer
    restart: unless-stopped
    ports:
      - "7777:80" #default mqtt-explorer port
  
  # InfluxDB
  influxdb: 
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
     - DOCKER_INFLUXDB_INIT_MODE=setup
     - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME:-admin}
     - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-admin}
     - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG:-default_org}
     - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET:-influxdb}
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
  
  # Telegraf
  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    restart: unless-stopped
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME:-admin}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-admin}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${DOCKER_INFLUXDB_INIT_ORG:-default_org}
      - INFLUXDB_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET:-influxdb}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mqtt5
      - influxdb
  
  # Grafana
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    
  # Node-Red
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ:-America/Bogota}
      - NODE_RED_CREDENTIAL_SECRET=${NODE_RED_CREDENTIAL_SECRET:-changeme}
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    depends_on:
      - mqtt5
      - influxdb

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:
  influxdb_data:
  grafana_data:

networks:
  default:
    name: mqtt5-network
